version: "3.9"
services:
  db:
    image: postgres:13.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: pappu687
    ports:
      - 8080:8080

  mockoon:
    image: mockoon/cli:latest
    ports:
      - "8001:8001"
    volumes:
      - ./mockoon:/data
    command: --port 8001 --data /data/odyssey-mock-api.json --container

volumes:
  postgres:
